version: '3'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./web/:/var/www/html/
  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'delete_me'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql:delegated
    depends_on: 
      - php
  php:
    image: php:7.2-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./web/:/var/www/html/
